local current_dir = ({reaper.get_action_context()})[2]:match('^.+[\\//]')
local root_dir = current_dir:match('^(.+/)tests/')
local auto_gen_dir = root_dir .. 'tools/autogenerated_modules/'

-- Update package.path to include the root directory and models directory
package.path = package.path .. ';' .. auto_gen_dir .. '?.lua;'

-- Debugging paths
reaper.ShowConsoleMsg("Current script path: " .. current_dir .. "\n")
reaper.ShowConsoleMsg("Root path added: " .. root_dir .. "\n")
reaper.ShowConsoleMsg("Auto gen path added: " .. auto_gen_dir .. "\n")
reaper.ShowConsoleMsg("Updated package.path: " .. package.path .. "\n")


local MediaTrack = require('media_track')
local ReaProject = require('rea_project')
local Reaper = require('reaper')
local MediaItem = require('media_item')
local MediaItemTake = require('media_item_take')
local TrackFX = require('track_fx')
local project = ReaProject:new()
local media_item_take = MediaItemTake:new()
local rea = Reaper:new() -- avoid using the name reaper as it is a global variable in reaper API
project:log('Rea project test')

media_item_take:log('Media item take test')
rea:log('Reaper test')
local sel_track = project:count_selected_tracks()
project:log('Selected tracks: ' .. sel_track)
local track = project:get_track(0)
track:log('Track 0')
local media_item = track:add_media_item_to_track()
media_item:log('Media item')
media_item:set_length(10, true)
local TrackFX = TrackFX:new(track, 0)
TrackFX:log('TrackFX')
local count = TrackFX:get_count()
TrackFX:log('TrackFX count: ' .. count)
local guid = TrackFX:get_fxguid()
TrackFX:log('TrackFX guid: ' .. guid)
local fx_idx = 0x2000000 + 4
TrackFX:log('TrackFX fx_idx: ' .. fx_idx)
local fx_name = TrackFX:get_fx_name(fx_idx)
TrackFX:log('TrackFX.pointer: ' .. TrackFX.pointer)
TrackFX:log(fx_name)
local retval, buf = reaper.TrackFX_GetNamedConfigParm(track.pointer, 0, "container_item.0")
TrackFX:log('TrackFX GetNamedConfigParm: ' .. buf)
