from pathlib import Path

MODULE_GEN_DIR = Path(__file__).parent
TOOLS_DIR = MODULE_GEN_DIR.parent
TEMPLATES_DIR = MODULE_GEN_DIR / "templates"
HTML_DIR = MODULE_GEN_DIR / "html"
API_HTML = (
    HTML_DIR / "ReaScript API — Documentation.html"
)  # downloaded from https://www.extremraym.com/cloud/reascript-doc/
AUTOGENERATED_MODULES = TOOLS_DIR / "autogenerated_modules"
REAPER_TYPES = (
    "MediaTrack",
    "MediaItem",
    "ReaProject",
    "AudioAccessor",
    "PCM_source",
    "TrackEnvelope",
    "MediaItemTake",
    "HWND",
    "AudioAccessor",
)
REA_FUNC_NAMESPACES = (
    "Blink",
    "BR",
    "CF",
    "CSurf",
    "Dock",
    "Envelope",
    "FNG",
    "Fab",
    # "GR",
    # "GSC",
    "GU",
    "ImGui",
    "JB",
    "JS",
    "LICE",
    "Llm",
    # "Loop",
    "MCULive",
    "joystick",
    "MIDI",
    "MIDIEditor",
    "MRP",
    "Main",
    "Master",
    "Menu",
    "NF",
    "PCM",
    "ReaPack",
    "SNM",
    "TakeFX",
    "ThemeLayout",
    "TimeMap",
    "Track",
    "TrackCtl",
    "TrackFX",
    "TrackFX",
    "TrackList",
    # "ULT",
    "Xen",
)
