from pathlib import Path

MODULE_GEN_DIR = Path(__file__).parent
TOOLS_DIR = MODULE_GEN_DIR.parent
TEMPLATES_DIR = MODULE_GEN_DIR / "templates"
HTML_DIR = MODULE_GEN_DIR / "html"
API_HTML = (
    HTML_DIR / "ReaScript API — Documentation.html"
)  # downloaded from https://www.extremraym.com/cloud/reascript-doc/
AUTOGENERATED_CODE = TOOLS_DIR / "autogenerated_code"
